name: flutter_login_app
description: A Flutter project demonstrating Firebase login.

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
